version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: elrefugio-db
    environment:
      POSTGRES_USER: elrefugio
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elrefugio
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth:
    build: ./backend
    container_name: elrefugio-auth
    env_file:
      - ./backend/.env_micro
    environment:
      - AUTH_PORT=5001
      - DATABASE_URL=postgresql://elrefugio:password@postgres:5432/elrefugio
    command: node dist/services/auth/index.js
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  messages:
    build: ./backend
    container_name: elrefugio-messages
    env_file:
      - ./backend/.env_micro
    environment:
      - MESSAGE_PORT=5002
      - DATABASE_URL=postgresql://elrefugio:password@postgres:5432/elrefugio
    command: node dist/services/messages/index.js
    ports:
      - "5002:5002"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres

  gif:
    build: ./backend
    container_name: elrefugio-gif
    env_file:
      - ./backend/.env_micro
    environment:
      - GIF_PORT=5003
      - GIPHY_API_KEY=0F7GPQyRtxvMtAm7kCxCZKnUYe30mjnL
    command: node dist/services/gif/index.js
    ports:
      - "5003:5003"

volumes:
  db-data:
